// Dati articoli, estratti dal Catalogo Merchandising SPX 26-27 (V.7)
const PRODUCTS = {
  'tshirt-allenamento-gialla': {
    name: 'T-Shirt Allenamento Gialla',
    category: 'T-Shirt',
    brand: 'B&C',
    price: '€ 10',
    material: '100% cotone ring-spun (col. AS600: 99% cotone, 1% viscosa — col. SG620: 85% cotone, 15% viscosa)',
    description: 'T-shirt girocollo sottile a costine, manica corta, struttura con busto tubolare, taglio moderno. Stampa in serigrafia.',
    thumb: 'assets/merch/tshirt-allenamento-gialla.jpg',
    image: 'assets/merch/large/tshirt-allenamento-gialla.jpg',
    sizeTables: [
      { title: 'Taglie Adulto', colA: 'Altezza', colB: 'Larghezza', rows: [['XS',68,45],['S',70,48],['M',72,51],['L',74,54],['XL',76,57],['XXL',78,60]] },
      { title: 'Taglie Bimbo', colA: 'Altezza', colB: 'Larghezza', rows: [['9/11',56,42],['12/14',63,45]] },
    ],
  },
  'tshirt-prepartita-nera': {
    name: 'T-Shirt Pre Partita Nera',
    category: 'T-Shirt',
    brand: 'B&C',
    price: '€ 10',
    material: '100% cotone ring-spun (col. AS600: 99% cotone, 1% viscosa — col. SG620: 85% cotone, 15% viscosa)',
    description: 'T-shirt girocollo sottile a costine, manica corta, struttura con busto tubolare, taglio moderno. Stampa in serigrafia.',
    thumb: 'assets/merch/tshirt-prepartita-nera.jpg',
    image: 'assets/merch/large/tshirt-prepartita-nera.jpg',
    sizeTables: [
      { title: 'Taglie Adulto', colA: 'Altezza', colB: 'Larghezza', rows: [['XS',68,45],['S',70,48],['M',72,51],['L',74,54],['XL',76,57],['XXL',78,60]] },
      { title: 'Taglie Bimbo', colA: 'Altezza', colB: 'Larghezza', rows: [['9/11',56,42],['12/14',63,45]] },
    ],
  },
  'felpa-nera': {
    name: 'Felpa Nera',
    category: 'Felpe',
    brand: 'Russell',
    price: '€ 45 / € 25 (bimbo)',
    material: '80% cotone, 20% poliestere',
    description: 'Felpa a tre strati con cappuccio e cordoncino piatto, maniche set-in, nastro di rinforzo al collo, felpata internamente, struttura con cuciture laterali. Nelle taglie Uomo il logo è cucito, con cucitura scritta sul cappuccio. Nelle taglie Bimbo il logo è stampato, senza stampa sul cappuccio.',
    thumb: 'assets/merch/felpa-nera.jpg',
    image: 'assets/merch/large/felpa-nera.jpg',
    sizeTables: [
      { title: 'Taglie Adulto', colA: 'Altezza', colB: 'Larghezza', rows: [['XS',64,51],['S',66,54],['M',69,57],['L',71,60],['XL',74,63],['XXL',76,66]] },
      { title: 'Taglie Bimbo', colA: 'Altezza', colB: 'Larghezza', rows: [['9/10',57,42],['11/12',62,45],['13/14',67,48]] },
    ],
  },
  'polo-rappresentanza': {
    name: 'Polo di rappresentanza',
    category: 'Polo',
    brand: 'Stedman',
    price: '€ 25',
    material: '95% cotone filato ad anelli pettinato, 5% elastan — vero piqué di alta qualità, tessuto estendibile',
    description: 'Polo da uomo a maniche corte, polsini e collo con bordo a costine, 3 bottoni. Stampa del logo.',
    thumb: 'assets/merch/polo-rappresentanza.jpg',
    image: 'assets/merch/large/polo-rappresentanza.jpg',
    sizeTables: [
      { title: 'Taglie', colA: 'Altezza', colB: 'Larghezza', rows: [['S',70,48],['M',72,51],['L',74,54],['XL',77,57],['XXL',79,60]] },
    ],
  },
  'giacca-softshell': {
    name: 'Giacca Softshell',
    category: 'Giacca',
    brand: 'BC',
    price: '€ 55',
    material: '94% poliestere, 6% elastane — tessuto a triplo strato (esterno softshell, interno traspirante, fodera micro-fleece)',
    description: 'Maniche set-in, cappuccio removibile con zip e regolabile con elastico, 2 tasche frontali con cerniera. Logo cucito.',
    thumb: 'assets/merch/giacca-softshell.jpg',
    image: 'assets/merch/large/giacca-softshell.jpg',
    sizeTables: [
      { title: 'Taglie', colA: 'Altezza', colB: 'Larghezza', rows: [['S',66,52],['M',69,55],['L',72,58],['XL',75,61],['XXL',78,64]] },
    ],
  },
  'pantaloni-lunghi': {
    name: 'Pantaloni Lunghi Felpati',
    category: 'Pantaloni',
    brand: 'Vesti',
    price: '€ 15',
    material: '70% cotone, 30% poliestere',
    description: 'Pantalone in felpa con costina. Logo stampato.',
    thumb: 'assets/merch/pantaloni-lunghi.jpg',
    image: 'assets/merch/large/pantaloni-lunghi.jpg',
    sizeTables: [
      { title: 'Taglie', colA: 'Lunghezza', colB: 'Larghezza', rows: [['S',99,34],['M',102,36],['L',105,37],['XL',108,39],['XXL',110,40]] },
    ],
  },
  'pantaloncini-corti': {
    name: 'Pantaloncini Corti Tuta',
    category: 'Pantaloncini',
    brand: 'BC',
    price: '€ 20',
    material: 'Parte esterna 100% cotone, parte interna 50% cotone / 50% poliestere',
    description: 'Pantaloncini in felpa french terry, tasche foderate in single jersey, tasca applicata sul retro, girovita a costine 1x1, cordini tondi con punta in metallo, occhielli in metallo, cuciture doppie, etichetta strappabile. Stampa scritta SPX.',
    thumb: 'assets/merch/pantaloncini-corti.jpg',
    image: 'assets/merch/large/pantaloncini-corti.jpg',
    sizeTables: [
      { title: 'Taglie', colA: 'Altezza', colB: 'Larghezza', rows: [['XS',44,35],['S',46,38],['M',48,40],['L',50,43],['XL',52,45],['XXL',54,48]] },
    ],
  },
  'pantaloncini-allenamento': {
    name: 'Pantaloncini Allenamento',
    category: 'Pantaloncini',
    brand: 'B&C',
    price: '€ 15',
    material: '100% poliestere',
    description: 'Stampa scritta SPX.',
    thumb: 'assets/merch/pantaloncini-allenamento.jpg',
    image: 'assets/merch/large/pantaloncini-allenamento.jpg',
    sizeTables: [
      { title: 'Taglie', colA: 'Altezza', colB: 'Larghezza', rows: [['XS',44,35],['S',46,38],['M',48,40],['L',50,43],['XL',52,45],['XXL',54,48]] },
    ],
  },
  'borsone-adrenalina': {
    name: 'Borsone grande Adrenalina',
    category: 'Borse e Zaini',
    price: '€ 25',
    description: 'Borsone grande con tasche porta scarpe sulle testate e tracolla. Stampa SPX sui lati.',
    thumb: 'assets/merch/borsone-adrenalina.jpg',
    image: 'assets/merch/large/borsone-adrenalina.jpg',
    sizeNote: 'Taglia unica',
  },
  'zaino-tracolla': {
    name: 'Zaino a tracolla',
    category: 'Borse e Zaini',
    price: '€ 20',
    description: 'Zaino con tracolla, stampa logo SPX.',
    thumb: 'assets/merch/zaino-tracolla.jpg',
    image: 'assets/merch/large/zaino-tracolla.jpg',
    sizeNote: 'Taglia unica',
  },
  'pochette': {
    name: 'Pochette',
    category: 'Borse e Zaini',
    price: '€ 10',
    description: 'Pochette porta oggetti con zip, stampa SPX.',
    thumb: 'assets/merch/pochette.jpg',
    image: 'assets/merch/large/pochette.jpg',
    sizeNote: 'Taglia unica',
  },
  'braccialetto-corda': {
    name: 'Braccialetto in corda',
    category: 'Accessori',
    price: '€ 2',
    description: 'Braccialetto in corda con logo in sublimatico. Tecnica: serigrafia, logo nero, dimensione 13×4 mm.',
    thumb: 'assets/merch/braccialetto-corda.jpg',
    image: 'assets/merch/large/braccialetto-corda.jpg',
    sizeNote: 'Taglia unica',
  },
  'berretto-visiera-curva': {
    name: 'Berretto con visiera curva',
    category: 'Accessori',
    price: '€ 15',
    description: 'Berretto con visiera curva, logo SPX applicato.',
    thumb: 'assets/merch/berretto-visiera-curva.jpg',
    image: 'assets/merch/large/berretto-visiera-curva.jpg',
    sizeNote: 'Taglia unica',
  },
  'berretto-invernale': {
    name: 'Berretto invernale',
    category: 'Accessori',
    price: '€ 15',
    description: 'Berretto invernale, logo SPX applicato.',
    thumb: 'assets/merch/berretto-invernale.jpg',
    image: 'assets/merch/large/berretto-invernale.jpg',
    sizeNote: 'Taglia unica',
  },
  'berretto-visiera-piatta': {
    name: 'Berretto con visiera piatta',
    category: 'Accessori',
    price: '€ 15',
    description: 'Berretto con visiera piatta, logo cucito.',
    thumb: 'assets/merch/berretto-visiera-piatta.jpg',
    image: 'assets/merch/large/berretto-visiera-piatta.jpg',
    sizeNote: 'Taglia unica',
  },
  'cuscino-gradinate': {
    name: 'Cuscino per gradinate',
    category: 'Accessori',
    price: '€ 20',
    description: 'Cuscino per gradinate, stampa in sublimatico.',
    thumb: 'assets/merch/cuscino-gradinate.jpg',
    image: 'assets/merch/large/cuscino-gradinate.jpg',
    sizeNote: 'Taglia unica',
  },
  'scaldacollo-pile': {
    name: 'Scaldacollo in pile',
    category: 'Accessori',
    price: '€ 10',
    description: 'Scaldacollo in pile, logo stampato.',
    thumb: 'assets/merch/scaldacollo-pile.jpg',
    image: 'assets/merch/large/scaldacollo-pile.jpg',
    sizeNote: 'Taglia unica',
  },
  'divisa-gara': {
    name: 'Divisa gara in sublimatico',
    category: 'Divisa Gara',
    price: '€ 35',
    description: 'Divisa gara ufficiale SPX Volley (maglia + pantaloncini), personalizzata con nome e numero del giocatore, sponsor di squadra, interamente stampata in sublimatico. Foto a titolo di esempio: nome, numero e sponsor variano in base a squadra e giocatore.',
    thumb: 'assets/merch/divisa-gara.jpg',
    image: 'assets/merch/large/divisa-gara.jpg',
    sizeNote: 'Taglie disponibili in fase d\'ordine nello store',
  },
};
